### ISSUE TITLE
Test Distribution Trigger failed with 422 with and without body

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#11]
Hi @fsaravia,
I am retesting the Distribution API with the node-red-m2x node.
I created a new distribution Sample Distribution (c7843ab616c930560d214fdb0572c4db)
And Also a data Stream (temp), and a device (f8cac6d64dc98e6b5bd3d6ce62ec876f).

When I try to test the trigger , I got 404 The specified trigger does not exists.

Am I missing something ?

The Request Details
================

new_msg.action = "testTrigger";
new_msg.topic = "distributions";
// Disribution ID
new_msg.topic_id = "c7843ab616c930560d214fdb0572c4db";
// Trigger ID
new_msg.sub_topic_id = "AUv5wfb8AVFihAVtqrGo";
new_msg.payload = {}
return new_msg;

**Comment by chenfli** [comment]
Same goes for Delete Trigger

**Comment by fsaravia** [comment]
Hi @chenfli, I just checked both endpoints you are reporting and both are working ok for distribution triggers. Can you add more details and a sample code so we can have more information on the issue?

Thanks

**Comment by chenfli** [comment]
HI @fsaravia,
My mistake, error in the node-red-m2x convertion name triggerID instead triggerId.
Closing.
