### ISSUE TITLE
Bug:  500 error on collection metadata Add/Update

### ISSUE THREAD

**Issue by sterlzbd** [attm2x/m2x-service#14]
I am getting a 500 error when I try to add/update the metadata of a collection. Both making a request with cURL and using [the website](https://m2x.att.com). 

The request headers from using the website:

```
PUT /v2/collections/1940fd63c8318dd50fb7c2c802c1e91d HTTP/1.1
Host: api-m2x.att.com
Connection: keep-alive
Content-Length: 129
Pragma: no-cache
Cache-Control: no-cache
Origin: https://m2x.att.com
X-CSRF-TOKEN: <CSRF Token>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Content-Type: application/json; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01
X-M2X-KEY: <MASTER API KEY>
Referer: https://m2x.att.com/devices?page=1&collection=1940fd63c8318dd50fb7c2c802c1e91d&tab=info
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
```
The payload:

```
{"name":"water_stations","description":null,"parent":null,"tags":"00010,00060,00065","metadata":{"owner":"sterling"}}
```

The response:
```
HTTP/1.1 500 Internal Server Error
Date: Thu, 29 Sep 2016 22:22:52 GMT
Server: nginx
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

And from developer tools console:

> XMLHttpRequest cannot load https://api-m2x.att.com/v2/collections/1940fd63c8318dd50fb7c2c802c1e91d. No 'Access-Control-Allow-Origin' header is present on the requested resource.

Let me know if there is any other info that would be helpful.

**Comment by jemc** [comment]
Thanks for reporting this issue.

We were able to reproduce the problem and find the cause quickly thanks to your detailed report.  It should now be fixed.

Feel free to reopen this ticket if you encounter the problem again.

Thanks!

**Comment by kristinpeterson** [comment]
@sterlzbd thanks for reporting! @jemc thanks for fixing!
