### ISSUE TITLE
M2X Node JS has error on deleteStreamValues

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#3]
Hi,
I recieve [function:deleteStreamValues] TypeError: Object [object Object] has no method 'del'
since the following code under m2x node.js implementation has a bug

// https://m2x.att.com/developer/documentation/v2/device#Delete-Device
Devices.prototype.deleteDevice = function(id, callback) {
  return this.del(helpers.url("/devices/%s", id), callback);
};

it should be fixed to 
// https://m2x.att.com/developer/documentation/v2/device#Delete-Device
Devices.prototype.deleteDevice = function(id, callback) {
  return this.client.del(helpers.url("/devices/%s", id), callback);
};

**Comment by chenfli** [comment]
The same in

// https://m2x.att.com/developer/documentation/v2/device#Delete-Device
Devices.prototype.deleteDevice = function(id, callback) {
  return this.del(helpers.url("/devices/%s", id), callback);
};

**Comment by grilix** [comment]
@chenfli thanks for reporting this issue. We just released the version 2.1.2 addressing the bug.
