### ISSUE TITLE
Update/Create DataStream on m2x returns positive answer (204) However, I cannot see the new stream on the m2x site

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#4]
How can I see data streams create per distribution ?

**Comment by Jbossalini** [comment]
The stream is not showing up under the Device?

**Comment by chenfli** [comment]
@Jbossalini, For a data stream that was generated from Distribution API we couldn't see any notification on the m2x site.
We done our tests at around 05:00 CST (+/- hour). The Device API works as planned. we used bvitinshtein@interwise.com (bvitinshtein user name) acocunt for this test.

It is not clear if we create a data stream from the Distribution API under which device it should reside (in our case there have2 devices, niether of them had a new Data stream even though the API returned a create response. The API doesn't require you to state the device you are creating it for.

**Comment by Jbossalini** [comment]
@chenfli I'm sure one of the developers will chime in, but I believe that adds a stream to the "template" that the Devices in the distribution get created from.  So, I would expect that the next time you create a Device under that distribution, it would have that new stream included.  In your case, create a 3rd device and it should be there.

**Comment by chenfli** [comment]
@Jbossalini, I will retest it under my account and return with the results. Thanks for your quick response.

**Comment by fsaravia** [comment]
@Jbossalini is right, you can create a new data stream on a certain device or on a distribution. If you create it on a distribution, it will appear on all devices created **after** that change. It will not affect existent devices.

**Comment by chenfli** [comment]
Ok, 
First for a distribution without any devices I got success

Request
========

payload:{ "unit": { "label": "celsius", symbol: "C" }, "type": "numeric" }, 
                        topic  : "distributions",
                        sub_topic_id : "Thermo",
                        topic_id : "3d6ecf7f2e3561dfc1a6bea16182a29f",
                        action : "updateDataStream"

Response:
=========

Successful M2X Api call [201]
{ payload:
   { name: 'Thermo',
     display_name: null,
     value: null,
     latest_value_at: null,
     type: 'numeric',
     unit: { label: 'celsius', symbol: 'C' },
     url: 'http://api-m2x.att.com/v2/distributions/3d6ecf7f2e3561dfc1a6bea16182a29f/streams/Thermo',
     created: '2015-02-03T20:26:21.484Z',
     updated: '2015-02-03T20:26:21.484Z' } }

As you can see from the  <a href="https://m2x.att.com/developer/documentation/v2/distribution#Create-Update-Data-Stream>document</a> and m2x-nodejs code there is no place to select the device on that distribution.

On the m2x.att.com, I cannot see any stream under the distribution view.
https://m2x.att.com/distributions/3d6ecf7f2e3561dfc1a6bea16182a29f (I did it on my account cfliesher@interwise.com (chenfli on GitHub).

So I am not sure where am I supposed to set the device in the request.  @esegev, @Jbossalini  any idea ?

One theory I have is that the stream is generated under the distribution and this part in the UI is not done yet there for I cannot see it on m2x.att.com.

Create/Update Data Stream
======================

PUT /distributions/{id}/streams/{name}

Update a data stream associated with the specified distribution (if a stream with this name does not exist it gets created).

Data streams accept only numeric values by default, this behavior can be configured by setting the type attribute to alphanumeric upon creation. Once a stream is created, it's type cannot be changed.

This request accepts the following parameters:

unit the unit used to measure this stream's values.
type the stream's type. This value can be numeric or alphanumeric and can only be specified when creating a data stream. (optional, type is numeric by default)



M2x Node js code
==============
// Create/Update a data stream associated with the distribution
//
// https://m2x.att.com/developer/documentation/v2/distribution#Create-Update-Data-Stream
Distributions.prototype.updateDataStream = function(id, name, params, callback) {
    return this.client.put(
        helpers.url("/distributions/%s/streams/%s", id, name),
        {
            headers: { "Content-Type": "application/json" },
            params: params
        },
        callback
    );
};

**Comment by chenfli** [comment]
Validated, only devices which creates from distribution gets the distributions streams. 
thanks @fsaravia
