### ISSUE TITLE
Inconsistence in JSON returning from M2X call

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#5]
Hi,
It appears that succesfull api calls returns **status**:20X field. While failed calls are returning **statusCode**:40X.

It would be great if the return field will have the same name, That way you don't need to do extra code on each call to parse for success,

I also found another exception:
The postValues  -https://m2x.att.com/developer/documentation/v2/device#Post-Data-Stream-Values
has a different way to return positive answer:

{ payload: { status: 'accepted' } }

instead 20X it return accepted.

**Comment by fsaravia** [comment]
@chenfli it appears that you are referring to an inconsistence in a client library and not the M2X service itself. Can you share which client are you using so we can track the inconsistence?

**Comment by chenfli** [comment]
sure, I am for my implementation of m2x I use 

https://www.npmjs.com/package/m2x

it is developed by @grilix / @seriousmoth , If this not the case on the rest API, than it needs to be fixed on that client.

**Comment by grilix** [comment]
@chenfli thanks for reporting this issue. I'll take a look into this.

**Comment by grilix** [comment]
@chenfli it looks like `status` is always available, here is a small example of some calls (being `./config` the config from the client example)..:

```javascript
var config = require("./config");
var M2X = require("m2x");
var m2xClient = new M2X(config.api_key);
var time = new Date().toISOString();

var callback = function(msg) {
  return function(res) { console.log(msg + ":", res.status); }; // display the response status, using 'status' for every response.
};

m2xClient.devices.view(config.device, callback("view device"));
m2xClient.devices.postValues(config.device, "load_1m", [{timestamp: time, value: 1}], callback("postValues"));
m2xClient.client.post("wrong-url", {}, callback("post wrong-url"));
m2xClient.client.post("/wrong-id", {}, callback("post wrong-id"));
m2xClient.client.get("wrong-url", callback("get wrong-url"));
m2xClient.client.get("/wrong-id", callback("get /wrong-id"));
m2xClient.client.get("/devices/" + config.device, callback("get /devices/" + config.device));
```

The output for this is:
```text
post wrong-url: 404
get wrong-url: 404
post wrong-id: 403
view device: 200
get /wrong-id: 403
get /devices/1a27836313fb0741df2781f6aa2475b5: 200
postValues: 202
```

Can you please post some example code of what you are trying to do, so we can have a better picture of the problem?

**Comment by chenfli** [comment]
@grilix I think I undersrand the problem, I think I looked to high in the JSON tree (looking only at a subset, msg.payload). I'll validate and close the issue.

**Comment by chenfli** [comment]
validated
