### ISSUE TITLE
Distribution Create Trigger API returns 422 Validation Error when Syntax is OK - using M2X node.js client

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#6]
@grilix , @fsaravia   hey,  

I am using the https://www.npmjs.com/package/m2x and trying to do 
https://m2x.att.com/developer/documentation/v2/distribution#Create-Trigger.

This is my request
------------------------
{payload:{ "stream": "testing_stream",
                                       "name": "test_trigger_distrib3",
                                       "condition": ">",
                                       "value": 30,
                                       "callback_url": "https://scrum-api-flow.att.io/sandbox/https/chenfli/in/flow",
                                       "status": "enabled" }, 
                             topic    : "distributions", 
                             action   : "createTrigger", 
                             topic_id : "1ee40764159d8b7bbc51e79916309e85"} // Distribution ID

I got 

{ payload: 'Validation Failed', statusCode: 422 }

I tried to add/remove sending location, The https is a valid address. I even test it on a distribution without a device and with 1 device. however, I am not sure what is wrong with my request ?

Please assist,
Thanks

Those are suppose to be the result of this API incase of validation error:
-------------------------------------------------------------------------------------------------
422 Unprocessable Entity
Content-Type: application/json

{ "message": "Validation Failed",
  "errors": { "stream": ["not_present"], "condition": ["not_valid"] } }

**Comment by chenfli** [comment]
Closed - My mistake error in the stream name

**Comment by chenfli** [comment]
Succes, but from some reason the m2x doesn't reflect it on the gui

This is thre response

{ payload: 
   { id: 'AUtanUPpTjhBGEzH1rnX',
     name: 'test_trigger_distrib3',
     stream: 'test_stream_distrib',
     condition: '>',
     value: 30,
     unit: 'C',
     callback_url: 'https://scrum-api-flow.att.io/sandbox/https/chenfli/in/flow',
     url: 'http://api-m2x.att.com/v2/distributions/1ee40764159d8b7bbc51e79916309e85/triggers/AUtanUPpTjhBGEzH1rnX',
     status: 'enabled',
     send_location: false,
     created: '2015-02-05T16:40:30.944Z',
     updated: '2015-02-05T16:40:30.944Z' } }

![image](https://cloud.githubusercontent.com/assets/1788314/6064481/fc61693e-ad66-11e4-86a9-929d08b6f2b6.png)

**Comment by chenfli** [comment]
And apperantly delete Trigger refuse to delete it from the resason it doesn't exists

Request
-----------
{topic    : "distributions",
                             action   : "deleteTrigger",
                             topic_id : "1ee40764159d8b7bbc51e79916309e85",
                             sub_topic_id :"AUtanUPpTjhBGEzH1rnX"

Response
-------------

{ statusCode: 404,
  payload: 'The specified trigger does not exist' }

any idea ?

**Comment by chenfli** [comment]
reoccurs, when creating the trigger from m2x site

![image](https://cloud.githubusercontent.com/assets/1788314/6103192/e6c4a574-b049-11e4-91d9-559fb5b78f3e.png)


curl -i  https://api-m2x.att.com/v2/distributions/6b6436846873b8dd34d410f8fd27af01/triggers -H "X-M2X-KEY: 3cf3bb243e288dcb343ddd65dd1b5302"
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 09 Feb 2015 08:49:25 GMT
Content-Type: application/json
Content-Length: 15
Status: 200 OK
X-M2X-VERSION: v2.6.0-alpha
Vary: Accept-Encoding
Vary: Accept

{"triggers":[]}

**Comment by fsaravia** [comment]
@chenfli  I can see that there is a mix of concepts here:

1. I checked that the trigger id `AUtanUPpTjhBGEzH1rnX` exists on M2X, it belongs to the distribution id `1ee40764159d8b7bbc51e79916309e85` and you should be able to access it (including edit and delete it) via said distribution.
2. On your latest message, you created a distribution against the **device** (not a distribution) with id `d868925...` (from the screenshot) but later you are trying to fetch it via the distribution id `6b6436846873b8dd34d410f8fd27af01`, that's why you aren't being able to access it.

I just checked all endpoints related to triggers and they seem to work ok, do you care to review again?
Thanks

**Comment by chenfli** [comment]
HI @fsaravia , It works now. However, I don't know if you have it in your documentation. 
It is important the following steps will occur in this order to create a trigger on a distribution:
1. Create a distribution.
2. Define the data streams for all the devices on that distribution.
3. Create the devices - this is the only way on the UI to validate the data streams actually created.
4. Create the Trigger.
