### ISSUE TITLE
Distribution - Delete Data Stream API - Return Postive doesn't reflect on the M2X WEb Site

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#7]
Hi @grilix / @fsaravia 
It appears the same behaviour as I saw on Create Trigger applies to delete data Stream.

Request
-----------

topic    : "distributions",
action   : "deleteDistribution",
topic_id : "3d6ecf7f2e3561dfc1a6bea16182a29f", // Distribution ID
sub_topic_id : "Thermo" //Stream Name

Response
-------------
{ payload: 
   { raw: '',
     headers: 
      { server: 'nginx',
        date: 'Thu, 05 Feb 2015 18:29:21 GMT',
        status: '204 No Content',
        'x-m2x-version': 'v2.6.0-alpha',
        vary: 'Accept' },
     status: 204,

The device is from the above distribution, the capture done after the API returned true

![image](https://cloud.githubusercontent.com/assets/1788314/6066563/a6cf0dd6-ad76-11e4-8a86-ce5d24419a63.png)

**Comment by fsaravia** [comment]
@chenfli as far as I can see, there is no distribution with the id `3d6ecf7f2e3561dfc1a6bea16182a29f`, the one on your screenshot has a different id, but I can tell that you also deleted it now, were you able to find a solution for the issue?

**Comment by fsaravia** [comment]
Closing this one as it became stale.
