### ISSUE TITLE
Distribution testTrigger return params not defined

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#8]
hi @grilix, we are testing the Distribution API, for m2x 2.1.2, the params argument is not defined there for I get this error, the code is attached:

// Test a trigger by firing a fake value
//
// https://m2x.att.com/developer/documentation/v2/distribution#Test-Trigger
Distributions.prototype.testTrigger = function(id, triggerId, callback) {
    return this.client.post(
        helpers.url("/distributions/%s/triggers/%s/test", id, triggerId),
        { params: **params**},
        callback
    );
};

**Comment by grilix** [comment]
@chenfli thanks for reporting this issue. It has been fixed on attm2x/m2x-nodejs version 2.1.3, and attm2x/m2x-javascript version 2.0.1.
