### ISSUE TITLE
testTrigger retrieves 405 for devices done by m2x node.js client

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#9]
Hi @grilix / @fsaravia ,
I am testing the triggers part  for the device,

The problem is as follows:

This method doesn't suppose to get params,
However, by the link it does required payload

however, with and without payload the result is the same 405

@fsaravia, what is the use case ?

// Test the specified trigger by firing it with a fake value.
//
// This method can be used by developers of client applications
// to test the way their apps receive and handle M2X notifications.
//
// https://m2x.att.com/developer/documentation/v2/device#Test-Trigger
Devices.prototype.testTrigger = function(id, triggerName, callback) {
    return this.client.post(
        helpers.url("/devices/%s/triggers/%s", id, triggerName),
        callback
    );
};

msg.topic_id is the distribution id
msg.sub_topic_id is the trigger id
msg.payload is params

there for it tranlates into 

msg.topic = "devices";
msg.action = "testTrigger";
msg.topic_id = "1d72bf0c5beaea24dfa10fd99f6e5da0";
msg.sub_topic_id = "AUtPzS7wk02lwGPcARSU";
msg .payload = {
  "device_id": "1d72bf0c5beaea24dfa10fd99f6e5da0",
  "stream": "Date",
  "trigger_name": "High Date",
  "trigger_description": "temperature > 30",
  "condition": ">",
  "threshold": 30.0,
  "value": 31.5,
  "timestamp": "2014-06-27T22:22:58.104Z",
  "location": {
               "name": "Machines room",
               "latitude": 40.77177,
               "longitude": -73.97352,
               "elevation": 0,
               "timestamp": "2014-06-27T22:22:57.040Z"
              }
}

I got 405, method not allowed.

**Comment by fsaravia** [comment]
Seems like the library is not calling the correct test endpoint which should be `POST /devices/{device_id}/triggers/{id}/test`. @grilix do you care to check when you get a moment please?

**Comment by grilix** [comment]
@fsaravia you are right, the endpoint path was wrong. Fixed on version 2.1.4.

**Comment by fsaravia** [comment]
@grilix thank you!

**Comment by chenfli** [comment]
@fsaravia, Can you please check if it necessary to pass the payload ? according to the documentation https://m2x.att.com/developer/documentation/v2/device#Test-Trigger it does.

the m2x nodejs client need to support passing location and other parameters, does this ability was removed on the m2x nodejs client ?

It is somehow confusing to the end users, since I redirect the users to the m2x help pages on the node red client. 

Notice that on distribution.testTrigger the ability to pass payload exists.

Your help is appreciated.

**Comment by grilix** [comment]
@chenfli it was my bad, sorry! I'll add the params.

**Comment by grilix** [comment]
@chenfli, version 2.1.5 released with this fix.

**Comment by chenfli** [comment]
Thanks @grilix,
@fergonzalez,  if you need another way to test the API you can use the m2x-node-red I made.

https://github.com/chenfli/M2X-Node-Red
https://www.npmjs.com/package/node-red-m2x

just install the node-red (http://nodered.org/) and npm install node-red-m2x from the main directory.

create the 4 nodes basic flow, and set the function nodes with the json I attached in this thread.

If you need any help with set this up, mail me I'll be more than happy to assist.

Cheers,
@chenfli

**Comment by fsaravia** [comment]
@grilix, @chenfli: Actually, there has been a confusion here, the test endpoint doesn't receive parameters on the API.
What the documentation states is that the `test` endpoint will send a callback to the url specified in the trigger definition and the server attending in that url is the one that will receive the payload that includes the trigger data and the device location. There's no need to send parameters to the `POST /devices/{device_id}/triggers/{id}/test`.

I hope this adds more clarification to the issue

**Comment by chenfli** [comment]
@fsaravia I am a bit confused.

Let's see if I got it right,  please confirm:

The payload that the callback url will recieve eventually cannot be defined by what you send as a json in the testTrigger API, but is a data that self generated by m2x mechanism.

Did I got it right ?

If that is so, than I will disregard the payload for on testTrigger both on device and distribution.

**Comment by fsaravia** [comment]
@chenfli yes, that is correct. At the moment the payload for the callback is generated by M2X and cannot be customised.

**Comment by chenfli** [comment]
Ok, @grilix I think I'll  just rollback to your previous version.

**Comment by grilix** [comment]
I've reverted the change and published as 2.1.6.
Now we have to remove the `params` from `Distributions.testTrigger`. Since it will break backwards compatibility, we'll have to release that as 2.2.0.

Does that sound good?

**Comment by grilix** [comment]
We've decided to keep 2.1 going, and release the fix as 2.1.7. The `params` on `Distributions` were never required by the API and has been removed from the client.

I'm sorry for the confusion on this issue, and I hope it's clear now. Your patience is very appreciated.
